summary of components. A little bit more detailed guide for devs
fullstacktf/myment-docs pull request #4
Opened 2019-07-27 10:54 UTC by pabloderivia

Just a little bit more detailed list of all the components we must create. We could open a new Issue with it too, if you consider it neccesary

2019-07-27 11:08 UTC, delirial requested changes
Some typo errors

2019-07-27 11:08 UTC, ArcaDelDelirio commented on front-docs/COMPONENTS_SUMMARY.md
> +#Components Summary
This must be # Component Summary not #Component Summary

2019-07-27 11:08 UTC, ArcaDelDelirio commented on front-docs/COMPONENTS_SUMMARY.md
> +##Description
Same than before
# Example
#Example

2019-07-27 11:08 UTC, ArcaDelDelirio commented on front-docs/COMPONENTS_SUMMARY.md
> +###Components
Ups

2019-07-27 15:00 UTC, pabloderivia commented on front-docs/COMPONENTS_SUMMARY.md
> +###Components
Gotcha

2019-07-27 17:29 UTC, armandodecanha commented on front-docs/COMPONENTS_SUMMARY.md
> +    - (VD)Nav buttons (free, custom, short)
(VD) Nav buttons (free, custom, short)

2019-07-27 17:35 UTC, armandodecanha approved these changes
There are some errors in the fragmentation of words, but I don't think it is relevant because it is a documentation for and among us. 

It's ok! 🎉

2019-07-30 12:15 UTC, delirial approved these changes
Good JOB!! This docs grow fast !!! Thanks 💯

2019-07-30 12:16 UTC, merged